name: Deploy LAMP App to AWS Lightsail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Lightsail
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload repo to server (to /home/bitnami/deploy)
        uses: appleboy/scp-action@v0.1.7
        with:
          debug: true
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.PEM_KEY }}
          source: |
              "./**"
              "!.git/**"        
          target: /home/bitnami/deploy
          overwrite: true

      - name: Move into Apache htdocs + set perms + restart
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.PEM_KEY }}
          script: |
            set -e
            # clean web root
            sudo rm -rf /opt/bitnami/apache/htdocs/*

            # copy only site assets from uploaded repo dir
            cd /home/bitnami/deploy
            sudo cp -r index.html add-contact.html login.html register.html view-contact.html css js images /opt/bitnami/apache/htdocs/

            # fix ownership/permissions
            sudo chown -R bitnami:daemon /opt/bitnami/apache/htdocs
            sudo find /opt/bitnami/apache/htdocs -type d -exec chmod 755 {} \;
            sudo find /opt/bitnami/apache/htdocs -type f -exec chmod 644 {} \;

            # restart apache
            sudo /opt/bitnami/ctlscript.sh restart apache

            echo "Deployment finished!"
