name: Deploy LAMP App to AWS Lightsail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Lightsail
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Upload site files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.PEM_KEY }}
          source: |
            index.html
            add-contact.html
            login.html
            register.html
            view-contact.html
            css/**
            js/**
            images/**
          target: /home/bitnami/deploy
          overwrite: true

      - name: Move into Apache htdocs + set perms + restart
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.PEM_KEY }}
          script: |
            set -e
            sudo rm -rf /opt/bitnami/apache/htdocs/*
            sudo mkdir -p /opt/bitnami/apache/htdocs
            sudo mv /home/bitnami/deploy/* /opt/bitnami/apache/htdocs/
            sudo chown -R bitnami:daemon /opt/bitnami/apache/htdocs
            sudo find /opt/bitnami/apache/htdocs -type d -exec chmod 755 {} \;
            sudo find /opt/bitnami/apache/htdocs -type f -exec chmod 644 {} \;
            sudo /opt/bitnami/ctlscript.sh restart apache
            echo "Deployment finished!"
